### ISSUE TITLE
User edit route refresh doesn't authenticate with cookies

### ISSUE THREAD

**Issue by jhosteny** [joscas/base_app#3]
Josep,

I don't have a test for this yet to show what's happening, but if you login as the admin user, navigate to the profile information, and refresh the page, you'll get a 401 and no redirect. I'm not sure I understand exactly why yet. It seems the user show route is an Auth route, so I thought it should be sending the cookie in that case?

Joe

**Comment by joscas** [comment]
Checked. It doesn't send a remember token when it should and thus the server replies with unauthorized. I'm going to investigate whether this is due to a bad config on the application side or otherwise it is an Ember-auth issue. I'll also implement a cuke test for that.

**Comment by jhosteny** [comment]
Great, thanks so much for the quick reply.

**Comment by joscas** [comment]
https://github.com/heartsentwined/ember-auth/issues/29

**Comment by joscas** [comment]
The ember-auth owner is currently working on an important refactoring that will solve a number of issues. Let's wait until next version to see if this gets fixed.

**Comment by joscas** [comment]
Latest update fixes this issue and adds a cucumber test for it. Solution is a workaround due to this ember.js issue: https://github.com/emberjs/ember.js/issues/2041

In any case now reload is possible.
