### ISSUE TITLE
Upgrade to ember-auth 5.0

### ISSUE THREAD

**Issue by ryw** [joscas/base_app#4]
@joscas I'm building my first Ember app, based on the project. I had some bugs that the new version of ember-auth resolves, but as a noob I'm struggling to translate this code to the new version.

I'm stuck right now with how to fix first line of this: https://github.com/joscas/base_app/blob/master/app/assets/javascripts/controllers/sign_in_controller.js

**Comment by joscas** [comment]
@ryw I'm right now working in upgrading the whole application to support ember-auth 5.0.  You can expect to see the new version pushed very soon (hopefully today) provided that @heartsentwined, the mantainer of ember-auth continues to be so responsive and fixes the small issues that arise.

Regarding the first line you mention, I think it has to revert back to this:

``` javascript
BaseApp.SignInController = Ember.Controller.extend({
```

**Comment by joscas** [comment]
https://github.com/heartsentwined/ember-auth/issues/43

**Comment by joscas** [comment]
The whole working file would be:

``` javascript
BaseApp.SignInController = Ember.Controller.extend({
  needs: ["users_edit"],

  email: null,
  password: null,
  remember: false,
  loginError: false,
  loginResponse: "",
  signIn: function() {
    BaseApp.Auth.signIn({
      data: {
        'email': this.get('email'),
        'password': this.get('password'),
        'remember': this.get('remember')
      }
    });
    var self = this;
    BaseApp.Auth.on('signInError', function() {
      self.set('loginError', true);
      self.set('loginResponse', BaseApp.Auth.get('jqxhr').statusText);
    });
    BaseApp.Auth.on('signInSuccess', function() {
      self.set('loginError', false);
    });
  },
  dismissError: function() {
    this.set('loginError', false);
  }
});
```

**Comment by heartsentwined** [comment]
@joscas I have nailed down the bug, it is a racing issue due to an oversight with events - I have no guarantee of their trigger sequence.

**Comment by joscas** [comment]
@heartsentwined Is it fixable? I hope it is :smile:

**Comment by heartsentwined** [comment]
Certainly fixable.

**Comment by joscas** [comment]
Project is now updated to latest ember-auth
