### ISSUE TITLE
Dealing with 401 (Unauthorized)

### ISSUE THREAD

**Issue by ryw** [joscas/base_app#5]
Thanks for the quick update @joscas to get the demo updated for the latest ember-auth.

I'm working on getting CRUD working for another model, and the hardest part for me is figuring out where and how to deal with the 401 Unauthorized issue.

Seems I need to ensure the user is signed in, so that I have a token for... getting the model without a 401.

I'm working on the show route, and using app/assets/javascripts/routes/users/show_route.js as a guide, but it doesn't work exactly because I don't have an object to transitionTo in the signInSuccess handler.

Would it be interesting to add another model to the project, so sample code for how to handle this problem would have a good home.

Thoughts? Have any sample code available to show how to deal with refreshing a URL that has a model that needs to be put behind authorization?
## 

Update: Actually users.index suffers from the same 401 Unauthorized problem that I'm dealing with.

So I can reload /users/:user_id page just fine, but /users yields 401 and redirects to route  actionRedirectable.signInRoute that is specified in ember-auth.

**Comment by joscas** [comment]
I will consider adding an extra model to the example. Regarding reload of urls for models that need authorization, the problem is the same as #3 and it involves a wider ember.js issue. Mainly models are loaded before user is signed in.  Currently a workaround is implemented for `users/show_route.js` but not for the index. I'll add the same solution to users index and simplify a little bit the current workaround (sorry that I won't be able to do that until monday)

**Comment by joscas** [comment]
In your additional model. Maybe you can transition to the same model route on sign in success. Also the route will have to load the model from the store because in this case, you can't just pick the user model autoloaded by ember-auth.

**Comment by ryw** [comment]
Yeah that's what I was trying to do, but I'm just too inexperienced with ember to figure out the right chain of events to be able to transition to a route that has a loaded model to reference

**Comment by joscas** [comment]
Working on adding additional model

**Comment by joscas** [comment]
Reloading pages with authorization is still an issue to be fixed. I closed #3 with a hack but a proper implementation would imply these Ember issues to be solved:

https://github.com/emberjs/data/issues/838
https://github.com/emberjs/ember.js/issues/2041

I continue working on this.
