### ISSUE TITLE
Lose session upon reload

### ISSUE THREAD

**Issue by asia653** [joscas/base_app#6]
Is it normal behaviour for this application to lose the user session upon a browser refresh?

**Comment by joscas** [comment]
It is not normal if you are signed in using remember me. Otherwise it is normal. What exactly are you doing? In case you are trying to reload an authenticated route (e.g. user edit) there is a pending issue with reload as explained in #5

**Comment by asia653** [comment]
Is this(lose session upon reload) normal behaviour for all ember applications? I wonder how ZenDesk does it. Looks like it is a non-issue though.
