### ISSUE TITLE
Application template rendering twice

### ISSUE THREAD

**Issue by jhosteny** [joscas/base_app#8]
Josep,

I suspect this is another issue with ember-auth / ember and not base_app, but I'm noticing something strange. If you look at the active_record branch (https://github.com/jhosteny/base_app) of my fork of your latest code, you can see that attempting to perform a render into a named outlet ('sidebar') inside of the application route's renderTemplate function, the whole thing is inserted twice.

I'm trying to see if I can understand why this is happening right now, but I'm wondering if perhaps you've noticed this?

To reproduce, you have to login and navigate to home, and then navigate to home again by refreshing the page.
- Joe

**Comment by joscas** [comment]
Hi Joe, I've noticed this effect before related to problems loading the model on an authenticated route when reloading the page. So again I would think this is due to trying to access and authenticated route after reload without having finished authentication before.

**Comment by jhosteny** [comment]
Josep,

Thanks. I suspected as much after finding where the view was being appended. Hopefully there's some movement on ember #2041 soon.

Joe

**Comment by joscas** [comment]
Closing this for the moment as it relates to an ember issue.
